### ISSUE TITLE
	PA viewing issue

### ISSUE THREAD

**Issue by amal-malamel** [eureka-clusters/pa-portal#37]
PA from one country can see data of projects in which they are not part of. 
Example 1) user name : Juana Sanchez
                     Country : Spain
                     She can see projects in which Spain is not a part of.
![image](https://user-images.githubusercontent.com/127127551/223470267-e7caeda1-136b-4cc4-bdee-26a2d46f4ae2.png)
![image](https://user-images.githubusercontent.com/127127551/223470340-206c217b-cd52-4c89-bf0b-e15adbbf3130.png)

**Comment by japaveh** [comment]
Duplicated: https://github.com/eureka-clusters/pa-portal/issues/36
