### ISSUE TITLE
Project Status Filter issue

### ISSUE THREAD

**Issue by amal-malamel** [eureka-clusters/pa-portal#39]
Suppose a project status filter is set and then we move to a particular page number with the filter set. After that, if we change the selected filter, the application will show the contents in the same page number with new filter. If there is no data to show there will be an error.
Example:  1)Goto Statistics-> Projects. Select the project status filter ‘Completed’ and move to page number 5.
                 2)Now deselect the filter and select the project status filter ‘Stopped’. 
                 3)In the output displayed, the application tries to show again page number 5 but because there is no data to show, it will show error.
 
Attaching the screenshot below,

![image](https://github.com/eureka-clusters/pa-portal/assets/127127551/9ecf2146-4345-4b44-80f3-31e811fadb57)

**Comment by japaveh** [comment]
This has been fixed, now no results are shown when the page is "out of bounds"
