### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by amal-malamel** [eureka-clusters/pa-portal#40]
Pagination style is changed and now we don’t have the issue that we had before. But the new style seems a little inconvenient for the users. For example, if user wants to move from the 11th page to 1st page, the user have to click 11 times. It would be nice and faster if we have buttons for that.

![image](https://github.com/eureka-clusters/pa-portal/assets/127127551/1bc3d61e-a9e1-4966-a72c-a74fe409e8cf)

**Comment by japaveh** [comment]
A brand new pagination component and table (based on tackstack/table) has been implemented, now the pagination issue has been resolved
